"""Constants for the NextEnergy Battery integration."""
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.const import (
    UnitOfEnergy,
    UnitOfPower,
    UnitOfTemperature,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfFrequency,
)

DOMAIN = "nextenergy_battery"
PLATFORMS = ["sensor"]
DEFAULT_POLLING_INTERVAL = 30
CONF_POLLING_INTERVAL = "polling_interval"

# Defines the structure of a sensor, including its name, register, scale, unit, device class, state class,
# whether it's a string, and the number of registers it occupies.
# (name, register, scale, unit, device_class, state_class, is_string, register_count)
SENSORS = {
    "model_name": ("Model Name", 30000, 1, None, None, None, True, 8),
    "serial_number": ("Serial Number", 30016, 1, None, None, None, True, 16),
    "master_version": ("Master Version", 36001, 1, None, None, None, False, 1),
    "slave_version": ("Slave Version", 36002, 1, None, None, None, False, 1),
    "manager_version": ("Manager Version", 36003, 1, None, None, None, False, 1),
    "bms_connection_status": ("BMS Connection Status", 37002, 1, None, None, None, False, 1),
    "bms_master_version": ("BMS Master Version", 37003, 1, None, None, None, False, 1),
    "bms_master_sn": ("BMS Master SN", 37005, 1, None, None, None, True, 16),
    "bms_slave_number": ("BMS Slave Number", 37032, 1, None, None, None, False, 1),
    "bms_slave_1_version": ("BMS Slave 1 Version", 37033, 1, None, None, None, False, 1),
    "bms_slave_1_sn": ("BMS Slave 1 SN", 37097, 1, None, None, None, True, 16),
    "bms_slave_2_version": ("BMS Slave 2 Version", 37034, 1, None, None, None, False, 1),
    "bms_slave_2_sn": ("BMS Slave 2 SN", 37113, 1, None, None, None, True, 16),
    "bms_slave_3_version": ("BMS Slave 3 Version", 37035, 1, None, None, None, False, 1),
    "bms_slave_3_sn": ("BMS Slave 3 SN", 37129, 1, None, None, None, True, 16),
    "bms_slave_4_version": ("BMS Slave 4 Version", 37036, 1, None, None, None, False, 1),
    "bms_slave_4_sn": ("BMS Slave 4 SN", 37145, 1, None, None, None, True, 16),
    "bms_slave_5_version": ("BMS Slave 5 Version", 37037, 1, None, None, None, False, 1),
    "bms_slave_5_sn": ("BMS Slave 5 SN", 37161, 1, None, None, None, True, 16),
    "bms_voltage": ("BMS Voltage", 37609, 0.1, UnitOfElectricPotential.VOLT, SensorDeviceClass.VOLTAGE, SensorStateClass.MEASUREMENT, False, 1),
    "bms_current": ("BMS Current", 37610, 0.1, UnitOfElectricCurrent.AMPERE, SensorDeviceClass.CURRENT, SensorStateClass.MEASUREMENT, False, 1),
    "bms_ambient_temp": ("BMS Ambient Temp", 37611, 0.1, UnitOfTemperature.CELSIUS, SensorDeviceClass.TEMPERATURE, SensorStateClass.MEASUREMENT, False, 1),
    "bms_soc": ("BMS SoC", 37612, 1, "%", SensorDeviceClass.BATTERY, SensorStateClass.MEASUREMENT, False, 1),
    "bms_soh": ("BMS SOH", 37624, 1, "%", None, SensorStateClass.MEASUREMENT, False, 1),
    "bms_remain_energy": ("BMS Remain Energy", 37632, 10, UnitOfEnergy.WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.MEASUREMENT, False, 1),
    "meter_connection_status": ("Meter Connection Status", 38801, 1, None, None, None, False, 1),
    "r_phase_voltage": ("R Phase Voltage", 38802, 0.1, UnitOfElectricPotential.VOLT, SensorDeviceClass.VOLTAGE, SensorStateClass.MEASUREMENT, False, 1),
    "s_phase_voltage": ("S Phase Voltage", 38804, 0.1, UnitOfElectricPotential.VOLT, SensorDeviceClass.VOLTAGE, SensorStateClass.MEASUREMENT, False, 1),
    "t_phase_voltage": ("T Phase Voltage", 38806, 0.1, UnitOfElectricPotential.VOLT, SensorDeviceClass.VOLTAGE, SensorStateClass.MEASUREMENT, False, 1),
    "r_phase_current": ("R Phase Current", 38808, 0.001, UnitOfElectricCurrent.AMPERE, SensorDeviceClass.CURRENT, SensorStateClass.MEASUREMENT, False, 1),
    "s_phase_current": ("S Phase Current", 38810, 0.001, UnitOfElectricCurrent.AMPERE, SensorDeviceClass.CURRENT, SensorStateClass.MEASUREMENT, False, 1),
    "t_phase_current": ("T Phase Current", 38812, 0.001, UnitOfElectricCurrent.AMPERE, SensorDeviceClass.CURRENT, SensorStateClass.MEASUREMENT, False, 1),
    "combined_active_power": ("Combined Active Power", 38814, 1, UnitOfPower.WATT, SensorDeviceClass.POWER, SensorStateClass.MEASUREMENT, False, 1),
    "frequency": ("Frequency", 38846, 0.01, UnitOfFrequency.HERTZ, SensorDeviceClass.FREQUENCY, SensorStateClass.MEASUREMENT, False, 1),
    "rated_power": ("Rated Power (Pn)", 39053, 0.001, UnitOfPower.KILO_WATT, SensorDeviceClass.POWER, None, False, 1),
    "max_active_power": ("Max Active Power (Pmax)", 39055, 0.001, UnitOfPower.KILO_WATT, SensorDeviceClass.POWER, None, False, 1),
    "status": ("Status", 39063, 1, None, None, None, False, 1),
    "grid_r_voltage": ("Grid R Voltage", 39123, 0.1, UnitOfElectricPotential.VOLT, SensorDeviceClass.VOLTAGE, SensorStateClass.MEASUREMENT, False, 1),
    "grid_s_voltage": ("Grid S Voltage", 39124, 0.1, UnitOfElectricPotential.VOLT, SensorDeviceClass.VOLTAGE, SensorStateClass.MEASUREMENT, False, 1),
    "grid_t_voltage": ("Grid T Voltage", 39125, 0.1, UnitOfElectricPotential.VOLT, SensorDeviceClass.VOLTAGE, SensorStateClass.MEASUREMENT, False, 1),
    "grid_frequency": ("Grid Frequency", 39139, 0.01, UnitOfFrequency.HERTZ, SensorDeviceClass.FREQUENCY, SensorStateClass.MEASUREMENT, False, 1),
    "inverter_temp": ("Inverter Temp", 39141, 0.1, UnitOfTemperature.CELSIUS, SensorDeviceClass.TEMPERATURE, SensorStateClass.MEASUREMENT, False, 1),
    "system_soc": ("System SoC", 39423, 1, "%", SensorDeviceClass.BATTERY, SensorStateClass.MEASUREMENT, False, 1),
    "active_power": ("Active Power", 39134, 0.001, UnitOfPower.KILO_WATT, SensorDeviceClass.POWER, SensorStateClass.MEASUREMENT, False, 1),
    "reactive_power": ("Reactive Power", 39136, 0.001, "kVar", SensorDeviceClass.REACTIVE_POWER, SensorStateClass.MEASUREMENT, False, 1),
    "grid_power_meter": ("Grid Power (Meter)", 39168, 1, UnitOfPower.WATT, SensorDeviceClass.POWER, SensorStateClass.MEASUREMENT, False, 1),
    "eps_power": ("EPS Power", 39216, 1, UnitOfPower.WATT, SensorDeviceClass.POWER, SensorStateClass.MEASUREMENT, False, 1),
    "load_power": ("Load Power", 39225, 1, UnitOfPower.WATT, SensorDeviceClass.POWER, SensorStateClass.MEASUREMENT, False, 1),
    "battery_power": ("Battery Power", 39237, 1, UnitOfPower.WATT, SensorDeviceClass.POWER, SensorStateClass.MEASUREMENT, False, 1),
    "load_consumption_today": ("Load Consumption Today", 39631, 0.01, UnitOfEnergy.KILO_WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.TOTAL_INCREASING, False, 2),
    "load_consumption_total": ("Load Consumption Total", 39629, 0.01, UnitOfEnergy.KILO_WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.TOTAL_INCREASING, False, 2),
    "grid_export_today": ("Grid Export Today", 39615, 0.01, UnitOfEnergy.KILO_WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.TOTAL_INCREASING, False, 2),
    "grid_export_total": ("Grid Export Total", 39613, 0.01, UnitOfEnergy.KILO_WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.TOTAL_INCREASING, False, 2),
    "grid_import_today": ("Grid Import Today", 39619, 0.01, UnitOfEnergy.KILO_WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.TOTAL_INCREASING, False, 2),
    "grid_import_total": ("Grid Import Total", 39617, 0.01, UnitOfEnergy.KILO_WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.TOTAL_INCREASING, False, 2),
    "battery_charge_today": ("Battery Charge Today", 39607, 0.01, UnitOfEnergy.KILO_WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.TOTAL_INCREASING, False, 2),
    "battery_charge_total": ("Battery Charge Total", 39605, 0.01, UnitOfEnergy.KILO_WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.TOTAL_INCREASING, False, 2),
    "battery_discharge_today": ("Battery Discharge Today", 39611, 0.01, UnitOfEnergy.KILO_WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.TOTAL_INCREASING, False, 2),
    "battery_discharge_total": ("Battery Discharge Total", 39609, 0.01, UnitOfEnergy.KILO_WATT_HOUR, SensorDeviceClass.ENERGY, SensorStateClass.TOTAL_INCREASING, False, 2),
}
